import { test, expect } from '@playwright/test'
import { readFileSync, mkdirSync } from 'node:fs'
const base = 'http://127.0.0.1:4174/bltbSch_201.github.io/rank/'
const liveBuild = 'http://127.0.0.1:4175/bltbSch_201.github.io/rank/'
const tile = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64')
mkdirSync('test-results/evidence', { recursive: true })

test('independent guide page works on production subpath, mobile and tablet', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto(liveBuild + 'guide/')
  await expect(page.getByRole('heading', { name: '下一站，去哪逛？' })).toBeVisible()
  for (const width of [1440, 768, 375]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/evidence/guide-empty-${width}.png`, fullPage: true })
  }
  await page.getByRole('button', { name: '地点目录 · 0' }).click()
  await expect(page.getByText('还没有收录店铺')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '下一站，去哪逛？' })).toBeVisible()
  await page.goto(liveBuild + 'guide/#/place/missing')
  await expect(page.getByRole('heading', { name: '没有找到这个条目' })).toBeVisible()
  await page.reload(); await expect(page.getByRole('heading', { name: '没有找到这个条目' })).toBeVisible()
  expect(errors).toEqual([])
})

test('photo-only board, fixed city colors, written detail and complete offline content', async ({ page }) => {
  await page.goto(base)
  const photo = page.locator('.photo-card').first()
  await expect(photo.locator('.card-link')).toHaveCSS('border-top-color', 'rgb(185, 91, 67)')
  await expect(photo.locator('.photo-caption')).toHaveCSS('opacity', '0')
  await page.getByLabel('显示名称与城市').check()
  await expect(photo.locator('.photo-caption')).toHaveCSS('opacity', '1')
  await photo.locator('a').click()
  await expect(page).toHaveURL(/\/rank\/guide\/#\/place\/demo-0$/)
  await expect(page.locator('.detail-text')).toContainText('<script>不是可执行内容</script>')
  const nav = new URL(await page.getByRole('link', { name: '去这里 · 高德地图' }).getAttribute('href') || '')
  expect(nav.searchParams.get('coordinate')).toBe('wgs84'); expect(nav.searchParams.get('callnative')).toBe('1')
  await expect(page.locator('.guide-detail')).toHaveCSS('border-top-color', 'rgb(185, 91, 67)')
  await page.reload(); await expect(page.locator('.detail-text')).toBeVisible()
  await page.setViewportSize({ width: 375, height: 900 })
  await page.reload()
  await expect(page.locator('.guide-detail h1')).toBeInViewport()
  await page.goto(base + '?q=很长')
  await page.getByRole('button', { name: '导出榜单' }).click()
  await page.getByLabel('完整内容 · HTML 图文存档').check()
  await page.getByRole('button', { name: '生成完整内容' }).click()
  const link = page.getByRole('link', { name: '下载完整内容（HTML）' })
  await expect(link).toBeVisible()
  let download = page.waitForEvent('download'); await link.click()
  await (await download).saveAs('test-results/evidence/full-content.html')
  let content = readFileSync('test-results/evidence/full-content.html', 'utf8')
  expect(content).toContain('data:image/svg+xml;base64,')
  expect(content).toContain('&lt;script&gt;不是可执行内容&lt;/script&gt;')
  expect(content).toContain('详细评价'); expect(content).not.toContain('不可见草稿')
  expect(content).not.toContain('虚构店铺 1（演示）')
  await page.getByLabel('完整榜单 · 28 个条目').check()
  await page.getByRole('button', { name: '重新生成' }).click()
  await expect(page.locator('dialog').getByRole('status')).toContainText('完整内容已生成')
  download = page.waitForEvent('download'); await link.click()
  await (await download).saveAs('test-results/evidence/full-board.html')
  content = readFileSync('test-results/evidence/full-board.html', 'utf8')
  expect(content).toContain('虚构店铺 27（演示）'); expect(content).not.toContain('不可见更新原因')
})

test('map and directory share colors, selection, filters and responsive layout', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  let tileRequests = 0
  await page.route('https://tile.openstreetmap.org/**', route => { tileRequests++; return route.fulfill({ contentType: 'image/png', body: tile }) })
  await page.goto(base + 'guide/')
  expect(tileRequests).toBe(0)
  await page.getByRole('button', { name: '加载互动地图' }).click()
  await expect(page.locator('.map-pin')).toHaveCount(4)
  await expect(page.locator('.map-pin').first()).toHaveCSS('background-color', 'rgb(185, 91, 67)')
  await page.locator('.map-pin-wrapper').first().click()
  await expect(page.locator('.detail-text')).toBeVisible()
  await expect(page.locator('.map-pin.selected')).toHaveCount(1)
  await page.getByLabel('城市筛选').selectOption('测试乙城')
  await expect(page.locator('.map-pin')).toHaveCount(2)
  await expect(page.locator('.place-directory nav a')).toHaveCount(14)
  await page.locator('.place-directory nav a').first().click()
  await expect(page.locator('.guide-detail h1')).toHaveText('虚构店铺 1（演示）')
  await expect(page.locator('.video-pending, video')).toHaveCount(0)
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await page.getByRole('button', { name: '查看全部位置' }).click()
  expect(tileRequests).toBeGreaterThan(0)
  for (const width of [1440, 768, 375]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/evidence/guide-fixture-${width}.png`, fullPage: true })
  }
  await page.getByRole('button', { name: '地点目录 · 28' }).click()
  await page.locator('.place-directory nav a').nth(5).click()
  await expect(page.getByText('位置待补充，暂不提供导航。')).toBeVisible()
  await page.getByRole('button', { name: '地图', exact: true }).click()
  await expect(page.locator('.place-map')).toBeVisible()
  await page.goto(base + 'guide/#/place/hidden')
  await expect(page.getByRole('heading', { name: '没有找到这个条目' })).toBeVisible()
  expect(errors).toEqual([])
})

test('map failure has a usable retry and directory fallback', async ({ page }) => {
  await page.route('https://tile.openstreetmap.org/**', route => route.abort())
  await page.goto(base + 'guide/')
  await page.getByRole('button', { name: '加载互动地图' }).click()
  await expect(page.getByText('底图暂时加载失败', { exact: false })).toBeVisible()
  await expect(page.locator('.place-directory nav a')).toHaveCount(28)
  await page.unroute('https://tile.openstreetmap.org/**')
  await page.route('https://tile.openstreetmap.org/**', route => route.fulfill({ contentType: 'image/png', body: tile }))
  await page.getByRole('button', { name: '重试底图' }).click()
  await expect(page.getByText('底图暂时加载失败', { exact: false })).toHaveCount(0)
})
