import { test, expect, type Page } from '@playwright/test'
import { mkdirSync } from 'node:fs'
const empty = 'http://127.0.0.1:4175/jimmyGu.github.io/rank/'
const fixture = 'http://127.0.0.1:4174/jimmyGu.github.io/rank/'
mkdirSync('test-results/evidence', { recursive: true })
async function noOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true) }
test('empty board: responsive layout, filters, invalid detail, exports', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto(empty)
  await expect(page.locator('.tier-label h3')).toHaveText(['夯', '顶级', '人上人', 'NPC', '拉完了'])
  await expect(page.locator('.tier-empty')).toHaveCount(5)
  await expect(page.locator('.place-card')).toHaveCount(0)
  for (const width of [1440, 768, 375]) {
    await page.setViewportSize({ width, height: 1000 }); await noOverflow(page)
    await page.screenshot({ path: `test-results/evidence/empty-${width}.png`, fullPage: true })
  }
  await page.getByRole('searchbox').fill('不存在')
  await expect(page.getByText('没有找到匹配的条目')).toBeVisible()
  await page.reload(); await expect(page.getByRole('searchbox')).toHaveValue('不存在')
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await expect(page.getByRole('searchbox')).toHaveValue('')
  await page.goto(empty + '#/place/missing'); await expect(page.getByRole('heading', { name: '没有找到这个条目' })).toBeVisible()
  await page.reload(); await expect(page.getByRole('heading', { name: '没有找到这个条目' })).toBeVisible()
  await page.getByRole('link', { name: '返回榜单', exact: true }).click()
  await page.getByRole('button', { name: '导出榜单' }).click()
  await page.getByRole('button', { name: '生成图片', exact: true }).click()
  await expect(page.locator('.download-list a')).toHaveCount(1)
  let download = page.waitForEvent('download'); await page.locator('.download-list a').click(); await (await download).saveAs('test-results/evidence/empty-compact.png')
  await page.getByLabel('短评长图 · 加上一句话评价').check()
  await page.getByRole('button', { name: '重新生成' }).click()
  await expect(page.locator('.download-list a')).toHaveCount(1)
  download = page.waitForEvent('download'); await page.locator('.download-list a').click(); await (await download).saveAs('test-results/evidence/empty-review.png')
  await page.keyboard.press('Escape'); await expect(page.locator('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '导出榜单' })).toBeFocused()
  expect(errors).toEqual([])
})
test('fixture: published data, stable rank, combined filters, details and history', async ({ page }) => {
  await page.goto(fixture)
  await expect(page.locator('.place-card')).toHaveCount(28)
  await expect(page.getByText('不可见草稿')).toHaveCount(0)
  await expect(page.getByText('不可见更新原因')).toHaveCount(0)
  await page.getByLabel('城市筛选').selectOption('测试甲城')
  await page.getByRole('searchbox').fill(' test ')
  await expect(page.locator('.place-card')).toHaveCount(14)
  await expect(page.locator('.rank-number').nth(1)).toContainText('#3')
  await page.reload(); await expect(page.locator('.place-card')).toHaveCount(14)
  await page.locator('.card-link').first().click()
  await expect(page.locator('.detail-text')).toContainText('第二段体验与理由')
  await expect(page.locator('.detail-heading')).toContainText('2026-09')
  await page.reload(); await expect(page.locator('.detail-text')).toBeVisible()
  await page.goBack(); await expect(page.locator('.place-card')).toHaveCount(14)
  await page.getByRole('button', { name: '重置', exact: true }).click()
  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 }); await noOverflow(page)
    await page.screenshot({ path: `test-results/evidence/fixture-${width}.png`, fullPage: true })
  }
  await page.goto(fixture + '#/place/hidden'); await expect(page.getByRole('heading', { name: '没有找到这个条目' })).toBeVisible()
})
test('fixture: export real images, Chinese, long names, filtered scope, pagination and retry', async ({ page }) => {
  await page.goto(fixture)
  await page.getByRole('button', { name: '导出榜单' }).click()
  await page.getByLabel('短评长图 · 加上一句话评价').check()
  await page.getByRole('button', { name: '生成图片', exact: true }).click()
  await expect(page.locator('.download-list a').first()).toBeVisible()
  const links = page.locator('.download-list a'), count = await links.count()
  expect(count).toBeGreaterThan(1)
  for (let i = 0; i < count; i++) {
    const download = page.waitForEvent('download'); await links.nth(i).click(); await (await download).saveAs(`test-results/evidence/fixture-review-${i + 1}.png`)
  }
  await page.getByLabel('简洁排序图 · 图片与名称').check(); await page.getByRole('button', { name: '重新生成' }).click()
  await expect(links.first()).toBeVisible()
  let download = page.waitForEvent('download'); await links.first().click(); await (await download).saveAs('test-results/evidence/fixture-compact.png')
  await page.getByRole('button', { name: '关闭导出' }).click()
  await page.getByRole('searchbox').fill('店铺 1（')
  await expect(page.locator('.place-card')).toHaveCount(1)
  await page.getByRole('button', { name: '导出榜单' }).click()
  await page.getByRole('button', { name: '生成图片', exact: true }).click()
  await expect(links).toHaveCount(1)
  download = page.waitForEvent('download'); await links.click(); await (await download).saveAs('test-results/evidence/filtered.png')
  await page.getByRole('button', { name: '关闭导出' }).click()
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await page.route('**/images/places/test.svg', route => route.abort())
  await page.getByRole('button', { name: '导出榜单' }).click(); await page.getByRole('button', { name: '生成图片', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('图片加载失败')
  await page.unroute('**/images/places/test.svg')
  await page.getByRole('button', { name: '生成图片', exact: true }).click(); await expect(links.first()).toBeVisible()
})
